language: cpp
compiler:
  - gcc
install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - apt-add-repository ppa:sonkun/sfml-stable
  - apt-add-repository ppa:sonkun/sfml-development
  - apt-get update
  - apt-get install sfml-development

script:
  - make